
ALTER TABLE jobs ALTER COLUMN job_type DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN description DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN work_mode DROP NOT NULL;
ALTER TABLE jobs ALTER COLUMN application_url DROP NOT NULL;
