export const PROJECT_TAG_OPTIONS_TABLE = 'project_tag_options'

export const DEFAULT_PROJECT_TAGS = [
  'Ada',
  'Adobe XD',
  'Agile',
  'Airflow',
  'Alpine.js',
  'Android',
  'Angular',
  'Ansible',
  'Apache',
  'Apache Kafka',
  'Apollo',
  'Arduino',
  'ASP.NET',
  'Astro',
  'Auth0',
  'AWS',
  'Azure',
  'Bash',
  'Big Data',
  'Blazor',
  'Bootstrap',
  'Bun',
  'C',
  'C#',
  'C++',
  'Cassandra',
  'Chakra UI',
  'Chart.js',
  'CI/CD',
  'Clean Architecture',
  'Clojure',
  'Cloudflare',
  'Cloud Computing',
  'COBOL',
  'Computer Vision',
  'Cordova',
  'CSS',
  'Cypress',
  'Dart',
  'Data Analytics',
  'Data Engineering',
  'Data Science',
  'Deno',
  'Design Patterns',
  'DevOps',
  'DigitalOcean',
  'Django',
  'Docker',
  'Domain-Driven Design',
  'DynamoDB',
  'Electron',
  'Elixir',
  'Elm',
  'Ember.js',
  'Erlang',
  'ESLint',
  'Excel',
  'Express',
  'FastAPI',
  'Fastify',
  'Figma',
  'Firebase',
  'Flask',
  'Flutter',
  'Front-end',
  'Full-stack',
  'Game Dev',
  'Gatsby',
  'Git',
  'GitHub Actions',
  'GitLab CI',
  'Go',
  'Google Cloud',
  'GraphQL',
  'gRPC',
  'Hadoop',
  'Hasura',
  'Haskell',
  'HTML',
  'Ionic',
  'IoT',
  'Java',
  'JavaScript',
  'Jenkins',
  'Jest',
  'jQuery',
  'JSON',
  'JWT',
  'Kafka Streams',
  'Kotlin',
  'Kubernetes',
  'Laravel',
  'Less',
  'Linux',
  'Lua',
  'Machine Learning',
  'MariaDB',
  'Material UI',
  'Microservices',
  'Mobile',
  'MongoDB',
  'MySQL',
  'NestJS',
  'Next.js',
  'Nginx',
  'NLP',
  'Node.js',
  'NoSQL',
  'Nuxt',
  'Objective-C',
  'Oracle',
  'Pandas',
  'PHP',
  'Playwright',
  'PostgreSQL',
  'Power BI',
  'Prisma',
  'Progressive Web App',
  'Python',
  'PyTorch',
  'Qt',
  'RabbitMQ',
  'Ruby on Rails',
  'React',
  'React Native',
  'Redis',
  'Redux',
  'REST API',
  'Robotics',
  'Ruby',
  'Rust',
  'Sass',
  'Scala',
  'Scrum',
  'Security',
  'Serverless',
  'Shell Script',
  'Socket.io',
  'SolidJS',
  'Spring',
  'Spring Boot',
  'SQL',
  'SQLite',
  'Svelte',
  'Supabase',
  'Swift',
  'Tailwind CSS',
  'Tauri',
  'TensorFlow',
  'Terraform',
  'Testing Library',
  'Three.js',
  'TypeScript',
  'Unity',
  'Unreal Engine',
  'UX/UI',
  'Vercel',
  'Vite',
  'Vitest',
  'Vue',
  'Web Components',
  'WebAssembly',
  'WebSocket',
  'WordPress',
  'Xamarin',
  'XML',
  'Alembic',
  'Apache Commons',
  'Auth.js',
  'Axios',
  'bcrypt',
  'BeautifulSoup4',
  'Carbon',
  'Cryptography',
  'Dask',
  'date-fns',
  'dotenv',
  'Drizzle ORM',
  'Gson',
  'Guava',
  'Guzzle',
  'HTTPX',
  'Jupyter',
  'Lodash',
  'Log4j',
  'Mongoose',
  'Newtonsoft.Json',
  'Polars',
  'Sequelize',
  'Serilog',
  'SLF4J',
  'TanStack Query',
  'TanStack Table',
  'tRPC',
  'TypeORM',
  'Dados',
  'IA',
]

export type ProjectTagOption = {
  id: string
  name: string
  display_order: number | null
  is_active: boolean
}

export function normalizeTagName(name: string) {
  return name.trim().replace(/\s+/g, ' ')
}

export function uniqueTagNames(tags: string[]) {
  return Array.from(new Set(tags.map(normalizeTagName).filter(Boolean)))
}
